using System.ComponentModel.DataAnnotations;

namespace BSDCPolls.Contracts.Requests.Auth;

/// <summary>
/// Payload for registering a new account. Only a password is required;
/// the username is auto-generated by the system. No PII is collected.
/// </summary>
/// <param name="Password">
/// The user's chosen password. Must be at least 12 characters and contain at least one
/// uppercase letter, one lowercase letter, one digit, and one special character.
/// </param>
public sealed record RegisterRequest([Required] [MinLength(12)] string Password);
