using BSDCPolls.Api.Data.Entities;
using BSDCPolls.Api.Data.Infrastructure;
using BSDCPolls.Api.Data.ValueConverters;
using BSDCPolls.Contracts.Enums;
using Microsoft.EntityFrameworkCore;

namespace BSDCPolls.Api.Data;

/// <summary>
/// EF Core database context for the BSDCPolls platform.
/// Uses lazy-loading proxies (all navigation properties must be <c>virtual</c>).
/// Audit fields are stamped automatically by <see cref="AuditInterceptor"/>.
/// </summary>
public class BsdcPollsDbContext : DbContext
{
    /// <summary>Initialises a new instance with the given options.</summary>
    /// <param name="options">DbContext configuration options.</param>
    public BsdcPollsDbContext(DbContextOptions<BsdcPollsDbContext> options)
        : base(options)
    {
    }

    /// <summary>All registered users (no PII — username + Supabase sub only).</summary>
    public DbSet<ApplicationUser> ApplicationUsers => Set<ApplicationUser>();

    /// <summary>Historical username records for reuse prevention.</summary>
    public DbSet<UsernameHistory> UsernameHistories => Set<UsernameHistory>();

    /// <summary>Per-user privacy settings.</summary>
    public DbSet<UserPrivacySettings> UserPrivacySettings => Set<UserPrivacySettings>();

    /// <summary>Allowlist entries for users with AllowlistOnly invite permission.</summary>
    public DbSet<InviteAllowlistEntry> InviteAllowlistEntries => Set<InviteAllowlistEntry>();

    /// <summary>Live poll sessions.</summary>
    public DbSet<Poll> Polls => Set<Poll>();

    /// <summary>Questions within a poll session.</summary>
    public DbSet<PollQuestion> PollQuestions => Set<PollQuestion>();

    /// <summary>Selectable answer choices for a poll question.</summary>
    public DbSet<PollAnswerOption> PollAnswerOptions => Set<PollAnswerOption>();

    /// <summary>Participant votes on poll questions.</summary>
    public DbSet<PollSubmission> PollSubmissions => Set<PollSubmission>();

    /// <summary>Structured surveys with JSONB question trees.</summary>
    public DbSet<Survey> Surveys => Set<Survey>();

    /// <summary>Respondent answers to surveys.</summary>
    public DbSet<SurveyResponse> SurveyResponses => Set<SurveyResponse>();

    /// <summary>PDF uploads for document-upload questions.</summary>
    public DbSet<SurveyDocument> SurveyDocuments => Set<SurveyDocument>();

    /// <summary>Directed invitations to polls or surveys.</summary>
    public DbSet<Invitation> Invitations => Set<Invitation>();

    /// <summary>In-app notifications generated by invitations.</summary>
    public DbSet<Notification> Notifications => Set<Notification>();

    /// <summary>Append-only change history for all AuditableEntity subclasses.</summary>
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();

    /// <inheritdoc />
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        ConfigureApplicationUser(modelBuilder);
        ConfigureUsernameHistory(modelBuilder);
        ConfigureUserPrivacySettings(modelBuilder);
        ConfigureInviteAllowlistEntry(modelBuilder);
        ConfigurePoll(modelBuilder);
        ConfigurePollQuestion(modelBuilder);
        ConfigurePollAnswerOption(modelBuilder);
        ConfigurePollSubmission(modelBuilder);
        ConfigureSurvey(modelBuilder);
        ConfigureSurveyResponse(modelBuilder);
        ConfigureSurveyDocument(modelBuilder);
        ConfigureInvitation(modelBuilder);
        ConfigureNotification(modelBuilder);
        ConfigureAuditLog(modelBuilder);

        SeedSystemSentinel(modelBuilder);
    }

    private static void ConfigureApplicationUser(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationUser>(e =>
        {
            e.ToTable("application_users");
            e.HasKey(u => u.Id);
            e.HasIndex(u => u.Uid).IsUnique();
            e.HasIndex(u => u.Username).IsUnique();
            e.HasIndex(u => u.SupabaseUserId).IsUnique();

            // Self-referential audit FKs — restrict to avoid cascades
            e.HasOne(u => u.CreatedBy)
                .WithMany()
                .HasForeignKey(u => u.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(u => u.UpdatedBy)
                .WithMany()
                .HasForeignKey(u => u.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureUsernameHistory(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UsernameHistory>(e =>
        {
            e.ToTable("username_history");
            e.HasKey(h => h.Id);
            e.HasIndex(h => h.Uid).IsUnique();

            e.HasOne(h => h.User)
                .WithMany()
                .HasForeignKey(h => h.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(h => h.CreatedBy)
                .WithMany()
                .HasForeignKey(h => h.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(h => h.UpdatedBy)
                .WithMany()
                .HasForeignKey(h => h.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureUserPrivacySettings(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserPrivacySettings>(e =>
        {
            e.ToTable("user_privacy_settings");
            e.HasKey(p => p.Id);
            e.HasIndex(p => p.Uid).IsUnique();
            e.HasIndex(p => p.UserId).IsUnique();

            e.Property(p => p.InvitePermission)
                .HasConversion<int>();

            e.HasOne(p => p.User)
                .WithOne()
                .HasForeignKey<UserPrivacySettings>(p => p.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(p => p.CreatedBy)
                .WithMany()
                .HasForeignKey(p => p.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(p => p.UpdatedBy)
                .WithMany()
                .HasForeignKey(p => p.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureInviteAllowlistEntry(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InviteAllowlistEntry>(e =>
        {
            e.ToTable("invite_allowlist_entries");
            e.HasKey(a => a.Id);
            e.HasIndex(a => a.Uid).IsUnique();
            e.HasIndex(a => new { a.OwnerId, a.AllowedUserId }).IsUnique();

            e.HasOne(a => a.Owner)
                .WithMany()
                .HasForeignKey(a => a.OwnerId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(a => a.AllowedUser)
                .WithMany()
                .HasForeignKey(a => a.AllowedUserId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(a => a.CreatedBy)
                .WithMany()
                .HasForeignKey(a => a.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(a => a.UpdatedBy)
                .WithMany()
                .HasForeignKey(a => a.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigurePoll(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Poll>(e =>
        {
            e.ToTable("polls");
            e.HasKey(p => p.Id);
            e.HasIndex(p => p.Uid).IsUnique();
            e.HasIndex(p => new { p.CreatorId, p.Status, p.IsPublic });

            e.Property(p => p.Status)
                .HasConversion<int>();

            e.HasOne(p => p.Creator)
                .WithMany()
                .HasForeignKey(p => p.CreatorId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(p => p.CreatedBy)
                .WithMany()
                .HasForeignKey(p => p.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(p => p.UpdatedBy)
                .WithMany()
                .HasForeignKey(p => p.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigurePollQuestion(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PollQuestion>(e =>
        {
            e.ToTable("poll_questions");
            e.HasKey(q => q.Id);
            e.HasIndex(q => q.Uid).IsUnique();
            e.HasIndex(q => new { q.PollId, q.OrderIndex });

            e.HasOne(q => q.Poll)
                .WithMany(p => p.Questions)
                .HasForeignKey(q => q.PollId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(q => q.CreatedBy)
                .WithMany()
                .HasForeignKey(q => q.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(q => q.UpdatedBy)
                .WithMany()
                .HasForeignKey(q => q.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigurePollAnswerOption(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PollAnswerOption>(e =>
        {
            e.ToTable("poll_answer_options");
            e.HasKey(o => o.Id);
            e.HasIndex(o => o.Uid).IsUnique();

            e.HasOne(o => o.PollQuestion)
                .WithMany(q => q.AnswerOptions)
                .HasForeignKey(o => o.PollQuestionId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(o => o.CreatedBy)
                .WithMany()
                .HasForeignKey(o => o.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(o => o.UpdatedBy)
                .WithMany()
                .HasForeignKey(o => o.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigurePollSubmission(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PollSubmission>(e =>
        {
            e.ToTable("poll_submissions");
            e.HasKey(s => s.Id);
            e.HasIndex(s => s.Uid).IsUnique();
            e.HasIndex(s => new { s.PollQuestionId, s.RespondentId }).IsUnique();

            e.HasOne(s => s.PollQuestion)
                .WithMany(q => q.Submissions)
                .HasForeignKey(s => s.PollQuestionId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(s => s.SelectedOption)
                .WithMany(o => o.Submissions)
                .HasForeignKey(s => s.SelectedOptionId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(s => s.Respondent)
                .WithMany()
                .HasForeignKey(s => s.RespondentId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(s => s.CreatedBy)
                .WithMany()
                .HasForeignKey(s => s.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(s => s.UpdatedBy)
                .WithMany()
                .HasForeignKey(s => s.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureSurvey(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Survey>(e =>
        {
            e.ToTable("surveys");
            e.HasKey(s => s.Id);
            e.HasIndex(s => s.Uid).IsUnique();
            e.HasIndex(s => new { s.CreatorId, s.Status, s.IsPublic });

            e.Property(s => s.Status)
                .HasConversion<int>();

            e.Property(s => s.QuestionTree)
                .HasConversion(new SurveyQuestionTreeConverter())
                .HasColumnType("jsonb");

            e.HasOne(s => s.Creator)
                .WithMany()
                .HasForeignKey(s => s.CreatorId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(s => s.CreatedBy)
                .WithMany()
                .HasForeignKey(s => s.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(s => s.UpdatedBy)
                .WithMany()
                .HasForeignKey(s => s.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureSurveyResponse(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SurveyResponse>(e =>
        {
            e.ToTable("survey_responses");
            e.HasKey(r => r.Id);
            e.HasIndex(r => r.Uid).IsUnique();
            e.HasIndex(r => new { r.SurveyId, r.RespondentId }).IsUnique();

            e.Property(r => r.AnswersJson)
                .HasConversion(new SurveyAnswersConverter())
                .HasColumnType("jsonb");

            e.HasOne(r => r.Survey)
                .WithMany(s => s.Responses)
                .HasForeignKey(r => r.SurveyId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(r => r.Respondent)
                .WithMany()
                .HasForeignKey(r => r.RespondentId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(r => r.CreatedBy)
                .WithMany()
                .HasForeignKey(r => r.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(r => r.UpdatedBy)
                .WithMany()
                .HasForeignKey(r => r.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureSurveyDocument(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SurveyDocument>(e =>
        {
            e.ToTable("survey_documents");
            e.HasKey(d => d.Id);
            e.HasIndex(d => d.Uid).IsUnique();

            e.HasOne(d => d.SurveyResponse)
                .WithMany(r => r.Documents)
                .HasForeignKey(d => d.SurveyResponseId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(d => d.CreatedBy)
                .WithMany()
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(d => d.UpdatedBy)
                .WithMany()
                .HasForeignKey(d => d.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureInvitation(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Invitation>(e =>
        {
            e.ToTable("invitations");
            e.HasKey(i => i.Id);
            e.HasIndex(i => i.Uid).IsUnique();
            e.HasIndex(i => new { i.InviteeId, i.Status });

            e.Property(i => i.Status)
                .HasConversion<int>();

            e.HasOne(i => i.Inviter)
                .WithMany()
                .HasForeignKey(i => i.InviterId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(i => i.Invitee)
                .WithMany()
                .HasForeignKey(i => i.InviteeId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(i => i.Poll)
                .WithMany(p => p.Invitations)
                .HasForeignKey(i => i.PollId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(i => i.Survey)
                .WithMany(s => s.Invitations)
                .HasForeignKey(i => i.SurveyId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(i => i.CreatedBy)
                .WithMany()
                .HasForeignKey(i => i.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(i => i.UpdatedBy)
                .WithMany()
                .HasForeignKey(i => i.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureNotification(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Notification>(e =>
        {
            e.ToTable("notifications");
            e.HasKey(n => n.Id);
            e.HasIndex(n => n.Uid).IsUnique();
            e.HasIndex(n => new { n.RecipientId, n.IsRead });

            e.HasOne(n => n.Recipient)
                .WithMany()
                .HasForeignKey(n => n.RecipientId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(n => n.Invitation)
                .WithOne(i => i.Notification)
                .HasForeignKey<Notification>(n => n.InvitationId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(n => n.CreatedBy)
                .WithMany()
                .HasForeignKey(n => n.CreatedById)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(n => n.UpdatedBy)
                .WithMany()
                .HasForeignKey(n => n.UpdatedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureAuditLog(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(e =>
        {
            e.ToTable("audit_logs");
            e.HasKey(a => a.Id);

            e.Property(a => a.Id)
                .ValueGeneratedOnAdd();

            e.Property(a => a.Payload)
                .HasColumnType("jsonb");

            e.HasOne(a => a.PerformedBy)
                .WithMany()
                .HasForeignKey(a => a.PerformedById)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void SeedSystemSentinel(ModelBuilder modelBuilder)
    {
        // System sentinel user — Id=1, used as CreatedById/UpdatedById during bootstrapping
        // and by AuditInterceptor when no authenticated user is in scope.
        var sentinelUid = new Guid("00000000-0000-0000-0000-000000000001");
        var epoch = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        modelBuilder.Entity<ApplicationUser>().HasData(new
        {
            Id = 1,
            Uid = sentinelUid,
            Username = "system",
            SupabaseUserId = "SYSTEM",
            IsActive = false,
            CreatedOn = epoch,
            CreatedById = 1,
            UpdatedOn = epoch,
            UpdatedById = 1,
        });
    }
}
